fn main() {
    panic!("error");
    println!("error exit!")
}